"use client";
import Image from "next/image"; import Link from "next/link"; import {useState} from "react"; import "./motivation.css";
const links=[["New Here","/visit"],["Messages","/messages"],["Ministries","/ministries"],["Leadership","/leadership"],["Prayer","/prayer"]];
export default function Home(){const[open,setOpen]=useState(false);return <main className="mot"><header className="mot-nav"><Link href="/"><Image src="/images/church-logo.jpg" alt="Church of the Harvest" width={300} height={220} priority className="mot-logo"/></Link><nav className="mot-links">{links.map(([a,b])=><Link key={a} href={b}>{a}</Link>)}<Link href="#give" className="mot-give">Give</Link></nav><button className="mot-menu" onClick={()=>setOpen(true)}>☰</button></header><div className={`mot-menu-panel ${open?"open":""}`}><button onClick={()=>setOpen(false)}>×</button><nav>{links.map(([a,b])=><Link key={a} href={b} onClick={()=>setOpen(false)}>{a}</Link>)}<Link href="#give">Give</Link></nav></div>
<section className="mot-hero"><Image src="/images/congregation.jpg" alt="Church of the Harvest congregation" fill priority sizes="100vw"/><div className="mot-hero-copy"><div className="mot-label">Laurel, Mississippi · Join us Sunday at 10:00 AM</div><h1>Welcome to<br/><em>Church of the Harvest.</em></h1><p>A church family rooted in God&apos;s Word, built in love, and committed to seeing lives transformed through Jesus Christ.</p><div className="mot-actions"><Link href="/visit" className="mot-btn">Plan My Visit →</Link><Link href="/messages" className="mot-btn alt">Watch a Message</Link></div></div></section><section className="mot-service"><div><span>JOIN US THIS SUNDAY</span><br/><strong>10:00 AM · 342 Hoy Rd, Laurel, MS</strong></div><Link href="/visit" className="mot-btn alt">New Here? →</Link></section>
<section className="mot-intro"><div className="mot-intro-grid"><div className="mot-kicker">WELCOME HOME</div><div className="mot-intro-copy"><h2>There is a place here for everybody.</h2><p>Church is more than a service. It&apos;s people growing in faith, finding community, serving together and walking through life together.</p><Link href="/visit" className="mot-btn">Who We Are →</Link></div></div><div className="mot-photo-pair"><div className="mot-photo"><Image src="/images/family-community.jpg" alt="Church family" fill sizes="60vw"/></div><div className="mot-photo"><Image src="/images/church-community-formal.jpg" alt="Church community" fill sizes="40vw"/></div></div></section>
<section className="mot-section"><div className="mot-head"><div><div className="mot-kicker">WELCOME HOME</div><h2>Find your people.<br/>Find your place.</h2></div><p>There are many ways to connect, grow and serve at Church of the Harvest. Start where you are and find the community that fits your season.</p></div><div className="mot-ministries"><Link href="/ministries" className="mot-ministry"><Image src="/images/community-men.jpg" alt="Men of Standard" fill sizes="50vw"/><div><span>MINISTRY</span><h3>Men of Standard</h3></div></Link><Link href="/ministries" className="mot-ministry"><Image src="/images/church-community-formal.jpg" alt="Church community" fill sizes="50vw"/><div><span>COMMUNITY</span><h3>There&apos;s room for you</h3></div></Link></div></section>
<section className="mot-section dark"><div className="mot-head"><div><div className="mot-kicker">LATEST MESSAGE</div><h2>Messages from<br/>the house.</h2></div></div><div className="mot-sermon"><a className="mot-sermon-img" href="https://www.youtube.com/watch?v=7KwEhozE_Kc" target="_blank"><Image src="https://img.youtube.com/vi/7KwEhozE_Kc/maxresdefault.jpg" alt="Did You Come Expecting sermon" fill sizes="60vw"/></a><div className="mot-sermon-copy"><div className="mot-kicker">PASTOR ROBERT LEWIS</div><h3>Did You Come Expecting?</h3><p>Luke 6:12–15</p><a href="https://www.youtube.com/watch?v=7KwEhozE_Kc" target="_blank" className="mot-btn">Watch Now ▶</a></div></div></section>
<section className="mot-invite"><div className="mot-invite-img"><Image src="/images/congregation.jpg" alt="Church worship" fill sizes="50vw"/></div><div className="mot-invite-copy"><div className="mot-kicker">JOIN US THIS SUNDAY</div><h2>You&apos;re invited.</h2><p>Whether you&apos;re exploring faith, looking for a church home, or ready for a fresh start, there is a place for you at Church of the Harvest.</p><p><strong>Sunday · 10:00 AM</strong><br/>342 Hoy Rd, Laurel, MS 39443</p><Link href="/visit" className="mot-btn">Plan Your Visit →</Link></div></section>
<section id="give" className="mot-section"><div className="mot-head"><div><div className="mot-kicker">GENEROSITY</div><h2>Give with purpose.</h2></div><div><p>Cash App · $seedofharvest342</p><a href="https://cash.app/$seedofharvest342" target="_blank" className="mot-btn">Give Now →</a></div></div></section><footer className="mot-footer"><div><Image src="/images/church-logo.jpg" alt="Church of the Harvest" width={220} height={170}/><p>342 Hoy Rd · Laurel, Mississippi 39443</p></div><nav><Link href="/visit">New Here</Link><Link href="/messages">Messages</Link><Link href="/ministries">Ministries</Link><Link href="/leadership">Leadership</Link><Link href="/prayer">Prayer</Link></nav></footer></main>}
